### ISSUE TITLE
Azure CLI version rollback Lab 09  Task2: Step 2

### ISSUE THREAD

**Issue by tofusgh** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#144]
# Module: 02
#### Step: 02

Description of issue
Need to rollback Azure CLI version in order for lab to work
Repro steps:

**When trying to run the below commands the following error occurs:**

In the Bash session within the Cloud Shell pane, run the following to build an image from the Dockerfile and push the image to the new ACR.

 ACRNAME=$(az acr list --resource-group AZ500LAB09 --query '[].{​​​​​​​​​Name:name}​​​​​​​​​' --output tsv) az acr build --image sample/nginx:v1 --registry $ACRNAME --file Dockerfile .

![2021-07-16_10-16-45](https://user-images.githubusercontent.com/31666473/125962296-4edffd39-2853-4d72-9960-01030a75b66c.png)

**Steps to fix:**
The Lab 09 fix for Task 2 requires you to open the cloud shell and run these two commands:

Run the 2 commands below:

python -m pip install -U --force-reinstall pip
pip install azure-cli==2.25.0 --force-reinstall azure-cli

Then click restart the cloud shell by click in power button: 

And then rerun the commands in Task 2: #2:

ACRNAME=$(az acr list --resource-group AZ500LAB09 --query '[].{Name:name}' --output tsv)
az acr build --image sample/nginx:v1 --registry $ACRNAME --file Dockerfile .

**Comment by mikedan99** [comment]
@tofusgh thank you for opening this issue! My class encountered this issue today. Your fix works perfectly!

**Comment by beatazalewa** [comment]
**Steps which worked for me:**
The Lab 09 fix for Task 2 requires you to open the cloud shell and run these two commands:

Run the 2 commands below:
Instead of using this statement:
python -m pip install -U --force-reinstall pip **(it didn't work for me)**
I used this solution:
**/usr/bin/python -m pip install --upgrade pip**
Then:
pip install azure-cli==2.25.0 --force-reinstall azure-cli

Then click restart the cloud shell by click in power button:

And then rerun the commands in Task 2: #2:

ACRNAME=$(az acr list --resource-group AZ500LAB09 --query '[].{Name:name}' --output tsv)
az acr build --image sample/nginx:v1 --registry $ACRNAME --file Dockerfile .

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this issue while running the course

**Comment by serling1962** [comment]
MOC-Labs-Review did not encounter this issue while running the course
