### ISSUE TITLE
remove step that requires delete confirmation by entering storage account name

### ISSUE THREAD

**Issue by MOC-Labs-Review** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#308]
# Module: 03
#### Step: 04

Description of issue:

This step can be removed since the error message is generated when pressing Delete in step 3. You do not have to enter storage account number and press Delete again.

**Comment by serling1962** [comment]
Please identify the Module, Task, and Step detailed in the issue posting.

GitHub issue post: This step can be removed since the error message is generated when pressing Delete in step 3. You do not have to enter storage account number and press Delete again.

Response:  Delete is not found in step 3.  See below.

Please advise.
Task 5: Create a storage account with a file share
In this task, you will create a storage account with a file share and obtain the storage account key.

  1.  In the Azure portal, in the Search resources, services, and docs text box at the top of the Azure portal page, type Storage accounts and press the Enter key.
  2.  On the Storage accounts blade, click + Create.
  3.  On the Basics tab of the Create storage account blade, specify the following settings (leave others with their default values):
Setting
Value
Subscription
the name of the Azure subscription you are using in this lab
Resource group
AZ500LAB12
Storage account name
any globally unique name between 3 and 24 in length consisting of letters and digits
Location
(US) EastUS
Performance
Standard (general-purpose v2 account)
Redundency
Locally redundant storage (LRS)

  1.  On the Basics tab of the Create storage account blade, click Review + Create, wait for the validation process to complete, and click Create.
Note: Wait for the Storage account to be created. This should take about 2 minutes.


Serling A. Davis
he/him
Senior Content Developer
Security, Compliance, Identity and Management
Office: +1 214 4575779
***@***.******@***.***>

[Microsoft Logo]
[Microsoft Certified: Azure Security Engineer Associate]

From: MOC-Labs-Review ***@***.***>
Sent: Wednesday, March 1, 2023 8:57 AM
To: MicrosoftLearning/AZ500-AzureSecurityTechnologies ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftLearning/AZ500-AzureSecurityTechnologies] remove step that requires delete confirmation by entering storage account name (Issue #308)

Module: 03
Lab/Demo: 01
Task: 05
Step: 04

Description of issue:

This step can be removed since the error message is generated when pressing Delete in step 3. You do not have to enter storage account number and press Delete again.

-

**Comment by serling1962** [comment]
Issue not found.
