### ISSUE TITLE
Lab 10: Key Vault (Implementing Secure Data by setting up Always Encrypted) issue

### ISSUE THREAD

**Issue by prabhjotsinghbakshi** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#335]
# Module: 00
## Lab 10: Key Vault (Implementing Secure Data by setting up Always Encrypted)
Exercise 1: Deploy the base infrastructure from an ARM template
#### Step: 07-Click the Review and Create button, and confirm the deployment by clicking the Create button.

Description of issue
Template fail to succeed
![issue2](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/12583943/efff0f32-360d-4d78-8460-05f0f857762b)

**Comment by serling1962** [comment]
Please log a support ticket with Azure support.

{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'VMConfig'. Error message: \"Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: '.NET Framework 4.8 was installed, but a reboot is required. \r\n Please reboot the system and try to install/upgrade Chocolatey again.\r\nAt C:\\Windows\\TEMP\\chocolatey\\chocoInstall\\tools\\chocolateysetup.psm1:815 char:11\r\n+           throw \".NET Framework 4.8 w...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "
    }
}

**Comment by renaudwangler** [comment]
Hello.
Please reopen this issue since it is not an Azure issue: the Chocolatey install waits for a reboot of the vm after the .net framework is installed : it happens at eveyr try ....
We shoud recommend a VM reboot after it's provisionning in the lab instructions or investigate in the choco install process to ensure this reboot is automated.

**Comment by serling1962** [comment]
Please open a ticket with Azure support as previously noted. Azure support controls the virtual compute framework and underlying virtual infrastructure processes (i.e., automate a choco install reboot etc.)

**Comment by renaudwangler** [comment]
Sorry about that, English is not my native language. Do you mean each and every student should open an Azure support ticket in order for his/her lab to complete ?
I'm not sure of the feeling of students about the product quality :(
If only "one" ticket is needed for Azure support to correct the underlying problem, you (I mean MS Education) should leave this issue opened (since some trainers give feedback about a problem during classrom sessions and the problem is still present) and open a ticket to ba able to report information about this issue...

**Comment by serling1962** [comment]
Not each student. The first experience of the issue should be reported. A ticket was opened however, any additional ticket surely assist with escalating the anomaly. Again, it is not expected that each student submit an issue.

**Comment by renaudwangler** [comment]
Thanks for the quick answer (you underdstand what I mean when I write that on open Issue on github gives feedback about the problem and its progress)
