### ISSUE TITLE
Azure VM can't deploy in Lab 11, Exercise 1 due to EAH being disabled

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#397]
#### Step 5: In the PowerShell session within the Cloud Shell pane, run the following to create a new Azure virtual machine. 
`New-AzVm -ResourceGroupName "AZ500LAB131415" -Name "myVM" -Location 'EastUS' -VirtualNetworkName "myVnet" -SubnetName "mySubnet" -SecurityGroupName   "myNetworkSecurityGroup" -PublicIpAddressName "myPublicIpAddress" -PublicIpSku Standard -OpenPorts 80,3389 -Size Standard_DS1_v2`

Description of issue:
Deployment of AZ VM in PS fails due to EAH not being enabled on the Azure subscription [p1]. Manually enabling EAH through `Register-AzProviderFeature -FeatureName "EncryptionAtHost" -ProviderNamespace "Microsoft.Compute"` resolves the issue and allows you to deploy the VM [p2].

[p1]

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/94069201/c60e7780-9dd2-4c2d-a0a7-29d30621cc95)

[p2]

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/94069201/91617d80-3d0c-4244-b2ad-4924e7654e6b)

**Comment by serling1962** [comment]
What step is this command (Register-AzProviderFeature -FeatureName "EncryptionAtHost" -ProviderNamespace "Microsoft.Compute") syntax required?

New-AzVm -ResourceGroupName "AZ500LAB131415" -Name "myVM" -Location 'EastUS' -VirtualNetworkName "myVnet" -SubnetName "mySubnet" -SecurityGroupName   "myNetworkSecurityGroup" -PublicIpAddressName "myPublicIpAddress" -PublicIpSku Standard -OpenPorts 80,3389 -Size Standard_DS1_v2


From: SkillableBB ***@***.***>
Sent: Monday, November 27, 2023 9:46 AM
To: MicrosoftLearning/AZ500-AzureSecurityTechnologies ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftLearning/AZ500-AzureSecurityTechnologies] Azure VM can't deploy in Lab 11, Exercise 1 due to EAH being disabled (Issue #397)

Lab 11: Azure Monitor
Exercise 1: Deploy an Azure virtual machine
Task 1: Deploy an Azure virtual machine
Step 5: In the PowerShell session within the Cloud Shell pane, run the following to create a new Azure virtual machine.

New-AzVm -ResourceGroupName "AZ500LAB131415" -Name "myVM" -Location 'EastUS' -VirtualNetworkName "myVnet" -SubnetName "mySubnet" -SecurityGroupName "myNetworkSecurityGroup" -PublicIpAddressName "myPublicIpAddress" -PublicIpSku Standard -OpenPorts 80,3389 -Size Standard_DS1_v2

Description of issue:
Deployment of AZ VM in PS fails due to EAH not being enabled on the Azure subscription [p1]. Manually enabling EAH through Register-AzProviderFeature -FeatureName "EncryptionAtHost" -ProviderNamespace "Microsoft.Compute" resolves the issue and allows you to deploy the VM [p2].

[p1]

image.png (view on web)<https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/94069201/c60e7780-9dd2-4c2d-a0a7-29d30621cc95>

[p2]

image.png (view on web)<https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/94069201/91617d80-3d0c-4244-b2ad-4924e7654e6b>

-

**Comment by SkillableBB** [comment]
Hi Serling, the command is needed before deploying the VM in Lab 11 Exercise 1.

**Comment by serling1962** [comment]
Edits were applied in lab 11 exercise 1, step 5.
