### ISSUE TITLE
Lab #4 issues (ACR &AKS)

### ISSUE THREAD

**Issue by William-Storms** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#421]
# Module: 03
#### Step: N/A

Description of issue:
The resource provider Microsoft.ContainerServices is not registered in the lab environments and there are no instructions on how the learner can remediate this.

Additionally, the lab instructions (technically the CLI script provided) create the AKS cluster in eastus.  The lab environment has no quota in eastus.

Recommend either altering the lab subscriptions to have the appropriate services pre-registered and the appropriate VCPU quotas available in the eastus region, or providing instructions on how to register the service and altering the script to reflect a region that has appropriate quota (westus worked for me)

Repro steps:

1.
1.
1.

**Comment by brentd09** [comment]
We found that when the students run the CLI command, it tells them that the Resource Provider is not registered but that it will register it for them. So the first part of your issue may not be a major problem. Thanks

**Comment by William-Storms** [comment]
That is inaccurate.  In my class a few weeks ago, the CLI command did not auto-register the Resource Provider and I needed to walk them through the process of registering the Resource Provider.  This happened with all 12 of the learners that attempted the lab.

Regards,
Bill Storms
Microsoft Technical Trainer

**Comment by brentd09** [comment]
Ok Bill,

I am just telling you what happened in today's class. If you think what you experienced a few weeks ago is how it should still be, I can't help you with that!  
All of my students also said they cannot proceed with the lab because the quota issue you talked about now affects many regions, as they tried 4 different ones including WestUS. 

Things change in Azure all the time and a few weeks is a long time in Azure!
I am sorry if you have taken this personally. But that is not my intent.

Microsoft Please fix these issues, as Bill has stated that this has been going on for a couple of weeks now.

Brent Denny MCT

**Comment by William-Storms** [comment]
I apologize if I came off as irritated.  That was not my intention, and I should have put more thought into the fact that tone doesn't always translate well in email.  I was unaware that the default behavior had changed, but I am glad that it has become less of an issue.

Regards,
Bill Storms
Microsoft Technical Trainer

**Comment by brentd09** [comment]
All good!

:)

**Comment by SkillableKA** [comment]
I have confirmed this issue as well. We are reciving multiple tickets concerning this issue. In my testing the two following Resource Providers are required to complete this lab:  Microsoft.ContainerService and Microsoft.Compute

These have to be manually installed so I've been instructing users to register them via: az provider register --namespace Microsoft.xxxxx

I have completed two separate instances of this lab today and they are both required to be manually registered.

The Microsoft.ContainerService error will be displayed first when running: 

az aks create --name MyKubernetesCluster --resource-group AZ500LAB09 --location eastus --no-ssh-key --node-vm-size Standard_DS2_v2 --nodepool-name agentpool --node-count 1 --vm-set-type AvailabilitySet --network-plugin azure --dns-name-prefix MyKubernetesCluster-dns

![image](https://github.com/user-attachments/assets/9ccc6f33-a628-4724-94f7-3232b58d8d2e)

Then the regional quota restriction error will appear when you run the command again because the Microsoft.Compute resource provider isn't registered.

![image](https://github.com/user-attachments/assets/980b5700-6ff1-4be7-8645-63c2c79786fd)


![image](https://github.com/user-attachments/assets/72359215-5f6c-4f77-ba66-f566f9f66ad6)

**Comment by brentd09** [comment]
Ok, That sheds some light on the matter, I have discovered that my students manually registered the Microsoft.Compute provider, this is probably why the rest of the providers were registered automatically when the command line was run. 

I guess this is why Bill and I had slightly different outcomes... 

Still broken though! (Just Saying ;) )

**Comment by serling1962** [comment]
Please confirm the identity of the lab host provider where you experienced the issue.
